### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::54000

### ISSUE THREAD

**Issue by Tikam02** [livestyle/atom#29]
**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [livestyle-atom](https://github.com/livestyle/atom) package 0.2.9

Uncaught Error: listen EADDRINUSE :::54000

```
At events.js:160

Error: listen EADDRINUSE :::54000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at module.exports (/packages/livestyle-atom/lib/server.js:29:10)
    at /packages/livestyle-atom/lib/client.js:53:12)
    at WebSocket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at ClientRequest.onerror (/packages/livestyle-atom/node_modules/ws/lib/WebSocket.js:711:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  2x -0:36.3.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
astromac-ui 0.1.0 
astronomical-ui 0.22.5 
atom-html-preview 0.1.22 
atom-live-server 2.1.2 
atom-material-syntax 1.0.6 
atom-react-native-css 1.1.3 
atom-ternjs 0.18.3 
atom-typescript 11.0.3 
autoclose-html 0.23.0 
busy-signal 1.4.1 
color-picker 2.2.5 
css-comb 2.5.0 
css-snippets 1.1.0 
emmet 2.4.3 
glacier-darkula-syntax 1.1.7 
gpp-compiler 3.0.7 
hyperclick 0.0.40 
intentions 1.1.2 
language-html5-subtlegradient 0.1.0 
linter 2.1.4 
linter-ui-default 1.5.4 
livestyle-atom 0.2.9 
logo-file-icons 1.11.0 
minimap 4.28.2 
molecule-ubuntu 0.2.0 
native-color-picker 0.2.5 
nebula-ui 0.6.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
nuclide 0.228.0 
nuclide-format-js 0.0.36 
open-recent 5.0.0 
platformio-ide-terminal 2.5.0 
todo-show 1.11.0 
wordpress-api 1.2.2 
```

**Comment by rubielhum** [comment]
Problemas con The error was thrown from the livestyle-atom package. This issue has already been reported.
