### ISSUE TITLE
Failed to activate the livestyle-atom package

### ISSUE THREAD

**Issue by Nitrino** [livestyle/atom#30]
Failed starting plugin on Atom 1.19

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.4
**Thrown From**: [livestyle-atom](https://github.com/livestyle/atom) package 0.2.9

### Stack Trace

Failed to activate the livestyle-atom package

```
At Cannot read property 'getDomNode' of undefined

TypeError: Cannot read property 'getDomNode' of undefined
    at getLinesDomNode (/packages/livestyle-atom/lib/analyzer/hyperlink.js:101:58)
    at module.exports (/packages/livestyle-atom/lib/analyzer/hyperlink.js:85:5)
    at atom.workspace.observeTextEditors.editor (/packages/livestyle-atom/lib/analyzer/decorator.js:28:13)
    at Workspace.observeTextEditors (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:717:15)
    at module.exports (/packages/livestyle-atom/lib/analyzer/decorator.js:21:37)
    at module.exports (/packages/livestyle-atom/lib/analyzer/index.js:36:21)
    at analyzer.add.atom.config.observe.enabled (/packages/livestyle-atom/index.js:235:25)
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:625:13)
    at Config.module.exports.Config.observe (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:150:27)
    at setupAnalyzer (/packages/livestyle-atom/index.js:233:16)
    at Object.module.exports.activate (/packages/livestyle-atom/index.js:20:2)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:843:36
```

**Comment by enoversum** [comment]
Same here on Windows since at least 1.9.0-beta1.

**Comment by enoversum** [comment]
No news on this front :( ?

**Comment by sergeche** [comment]
This project is on-hold now, no further updates

**Comment by enoversum** [comment]
Ah, too bad, @sergeche, but thanks for letting us know :(.

**Comment by GrantColloty** [comment]
Any idea when we might see a fix for this? I was loving how this sped up my workflow. It's a really fantastic addition to any front end dev's toolbox.

**Comment by seyedabbasseyedi** [comment]
livestyle-atom not correct support but sublime better supoort
