### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by NickolasKyrylyuk** [livestyle/atom#32]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0-beta1 x64
**Electron**: 1.6.9
**OS**: �������� Windows 10 Pro
**Thrown From**: [livestyle-atom](https://github.com/livestyle/atom) package 0.2.9

### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At C:\Users\Elon Musk\.atom\packages\livestyle-atom\lib\analyzer\index.js:45

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at /packages/livestyle-atom/lib/analyzer/index.js:45:56)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.20.0-beta1/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.20.0-beta1/resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.20.0-beta1/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.20.0-beta1/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom/app-1.20.0-beta1/resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.20.0-beta1/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.20.0-beta1/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.20.0-beta1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.20.0-beta1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.20.0-beta1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.20.0-beta1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  4x -3:04.1.0 editor:newline (input.hidden-input)
     -2:34.4.0 autocomplete-plus:confirm (input.hidden-input)
     -2:34.3.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -2:28.1.0 core:save (input.hidden-input)
 15x -1:16.3.0 core:backspace (input.hidden-input)
     -1:13.6.0 autocomplete-plus:confirm (input.hidden-input)
     -1:13.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  5x -1:10.9.0 core:backspace (input.hidden-input)
     -1:03.9.0 core:save (input.hidden-input)
     -0:38.5.0 command-palette:toggle (input.hidden-input)
     -0:33.3.0 core:move-down (input.hidden-input)
     -0:32.3.0 core:confirm (input.hidden-input)
     -0:32.3.0 livestyle:show-widget (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 2.0.4 
autoclose-html 0.23.0 
busy-signal 1.4.3 
emmet 2.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-htmlhint 1.3.3 
linter-stylelint 4.0.1 
linter-ui-default 1.6.4 
livestyle-atom 0.2.9 
```

**Comment by ekil1100** [comment]
1. using the `livestyle:show-widget`, the error appears.

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.5
**Thrown From**: [livestyle-atom](https://github.com/livestyle/atom) package 0.2.10


### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /Users/Like/.atom/packages/livestyle-atom/lib/analyzer/index.js:45

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at /packages/livestyle-atom/lib/analyzer/index.js:45:57)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:152:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:106:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -6:37.9.0 markdown-writer:insert-new-line (input.hidden-input)
     -6:37.9.0 docblockr:parse-enter (input.hidden-input)
     -6:37.9.0 editor:newline (input.hidden-input)
     -6:36.8.0 core:paste (input.hidden-input)
     -6:33.2.0 core:undo (input.hidden-input)
     -6:25.3.0 core:paste (input.hidden-input)
     -6:22.7.0 core:save (input.hidden-input)
     -4:47.3.0 core:select-all (input.hidden-input)
     -4:46 core:paste (input.hidden-input)
  3x -4:43.7.0 core:save (input.hidden-input)
     -1:08.8.0 settings-view:open (input.hidden-input)
     -1:03.8.0 core:confirm (input.hidden-input)
     -0:28.1.0 command-palette:toggle (input.hidden-input)
     -0:24.8.0 core:move-down (input.hidden-input)
     -0:24.4.0 core:confirm (input.hidden-input)
     -0:24.4.0 livestyle:show-widget (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-busy-unifier-sb 1.0.3 
atom-ide-ui 0.12.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
autocomplete-paths 2.12.2 
browser-plus 0.0.98 
busy-signal 1.4.3 
city-lights-icons 1.1.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.5 
color-picker 2.3.0 
docblockr 0.13.7 
editorconfig 2.2.2 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.22 
highlight-selected 0.14.0 
ide-css 0.3.0 
language-babel 2.85.0 
language-dotfiles 1.1.0 
language-latex 1.1.1 
language-lua 0.9.11 
language-markdown 0.26.0 
linter-eslint 8.4.1 
livestyle-atom 0.2.10 
markdown-pdf 2.2.0 
markdown-writer 2.7.4 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
nuclide-format-js 0.0.46 
pdf-view 0.70.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.3 
prettier-atom 0.54.0 
project-manager 3.3.6 
set-syntax 0.4.0 
sort-lines 0.18.0 
sync-settings 0.8.6 
tool-bar 1.1.7 
tool-bar-main 0.0.11 
tool-bar-markdown-writer 0.3.1 
tree-view-git-status 1.5.0 
```
