### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::54000

### ISSUE THREAD

**Issue by JonSnow-JY** [livestyle/atom#41]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [livestyle-atom](https://github.com/livestyle/atom) package 0.2.10

### Stack Trace

Uncaught Error: listen EADDRINUSE :::54000

```
At events.js:160

Error: listen EADDRINUSE :::54000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at module.exports (/packages/livestyle-atom/lib/server.js:29:10)
    at /packages/livestyle-atom/lib/client.js:53:12)
    at Object.onceWrapper (events.js:290:19)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at ClientRequest.onerror (/packages/livestyle-atom/node_modules/ws/lib/WebSocket.js:711:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:14.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-formatter-jsbeautify 1.1.2 
autoclose-html 0.23.0 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.13 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-vue 0.23.1 
linter 2.0.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
livestyle-atom 0.2.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
open-in-browser 0.5.2 
pretty-json 1.6.4 
px2rem-plus 0.3.1 
```

**Comment by Cynth42** [comment]
What do I need to do to fix this error?
